### ISSUE TITLE
Crashes occur on older versions.

### ISSUE THREAD

**Issue by Chung-Chase52** [skydoves/Cloudy#33]
Crashes occur when running the Oreo version on the Device Manager.

code
ava.lang.NoSuchMethodError: No virtual method setAmbientShadowColor(I)Z in class Landroid/view/RenderNode; or its super classes (declaration of 'android.view.RenderNode' appears in /system/framework/framework.jar:classes2.dex)
                                        	at

**Comment by skydoves** [comment]
Hey @Chung-Chase52, which Cloudy version do you use?

**Comment by Chung-Chase52** [comment]
This is version 0.2.0

**Comment by skydoves** [comment]
https://issuetracker.google.com/issues/337665159#comment7

**Comment by skydoves** [comment]
@Chung-Chase52  It seems that there's a bug on the Android graphic layers for the specific Android versions (8 and 9), and it has been fixed on 1.7.0-beta04. I recommend you use the most recent Compose UI version (1.7.0-beta05).

**Comment by skydoves** [comment]
Hey @Chung-Chase52, Would you try to build again with the new release `0.2.1`?

**Comment by OgrVasSiem** [comment]
hey, On Android version 8 with Compose UI version 1.7.0, crashes also occur. The blur effect does not have time to load.

Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 60.  Wait queue head age: 20522.9ms.)

**Comment by JohnBetohn** [comment]
Hi
Issue still occurs with release 0.2.3 on Android 8 with Compose ui version 1.7.0-beta05.
The same ANR @OgrVasSiem mentioned.

**Comment by ervinsae** [comment]
Reason: Input dispatching timed out (Waiting because the touched window's input channel is full.  Outbound queue length: 1.  Wait queue length: 52.)
